### ISSUE TITLE
Add ignored paths to csrf validation

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-spa-4j#3]
When trying to integrate static page serving from a service that was protected, i notice that all paths are being blocked.

To get around this, would it be a good idea to add configuration to define paths where csrf validation would be ignored?

**Comment by stevehu** [comment]
That might be a good idea. /index.html, /images /css etc. Or we put the resource handler in the beginning in the request chain?

**Comment by NicholasAzar** [comment]
The resource handler is not a middleware but rather added to the HandlerProvider.. would u prefer that design to change?

**Comment by stevehu** [comment]
@NicholasAzar With the release 1.5.18, we can have a different chain to handler the static content so that CSRF handler is not part of it. Do you think that will work? Thanks.

**Comment by NicholasAzar** [comment]
@stevehu Yeah, this is no longer required
